name: Build wheels across platforms

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-11]

    steps:
      - name: Provide gfortran (macOS)
        if: runner.os == 'macOS'
        run: |
          # https://github.com/actions/virtual-environments/issues/2524
          # https://github.com/cbg-ethz/dce/blob/master/.github/workflows/pkgdown.yaml
          sudo ln -s /usr/local/bin/gfortran-12 /usr/local/bin/gfortran
          sudo ln -s /usr/local/bin/gcc-12 /usr/local/bin/gcc
          sudo mkdir /usr/local/gfortran
          sudo ln -s /usr/local/Cellar/gcc@12/*/lib/gcc/12 /usr/local/gfortran/lib
          gfortran --version
          gcc --version
          which gcc
          which gfortran

      - name: Provide fftw and ninja (macOS)
        if: runner.os == 'macOS'
        run: |
          # fftw3 
          brew install fftw ninja
          fftw-wisdom -V

      - name: Provide gfortran (Windows)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            git
            make

          pacboy: >-
            toolchain:p
            gcc-fortran:p
            openblas:p
            lapack:p
            fftw:p
            cmake:p
            ninja:p

      - name: Checkout repository
        uses: actions/checkout@v3

      # Used to host cibuildwheel
      - name: Setup python
        uses: actions/setup-python@v3

      - name: Build wheels (linux/macos)
        if: runner.os != 'Windows'
        uses: pypa/cibuildwheel@v2.11.1
        # to supply options, put them in 'env', like:
        env:
          CIBW_SKIP: cp36*
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: ""
        with: 
            package-dir: python

      - name: Build wheels (windows)
        if: runner.os == 'Windows'
        uses: pypa/cibuildwheel@v2.11.1
        # to supply options, put them in 'env', like:
        env:
          CIBW_SKIP: cp36*
          CIBW_ENVIRONMENT_WINDOWS: FC=gfortran F90=gfortran
        #with: 
        #    package-dir: python

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
